num1=float(input("Ingrese el numero: "))
num2=float(input("Ingrese el numero: "))
suma=(num1+num2)
resta=(num1-num2)
multiplicacion=(num1*num2)
division=(num1/num2)
print("La suma es: ",suma)
print("La resta es: ",resta)
print("La multiplicación es: ",multiplicacion)
print("La división es: ",division)
