print("Curso: Fundamentos de Python")
print("Estudiante: Evelyn Malo")
print("Fecha: 30/03/2023\n")
numeros=[1,2,3,4,5]
print("La lista es:")
print(numeros)
print("El tercer elemento de la lista es:")
print(numeros[2])
print("Modificar un elemento de la lista")
numeros.remove(4)
numeros.append(6)
print(numeros)
print("La lista agregada el 9 es:")
numeros.append(9)
print(numeros)
print("Lista sin el 2")
numeros.remove(2)
print(numeros)
print("Recorrer la lista con el bucle for")
for e in numeros:
    print(e)
print("Ordenar una lista")
numeros.reverse()
print(numeros)
print("La longitud de la lista")
print(len(numeros))
print("Comprobar si un elemento se encuentra en la lista")
'a' in numeros
print(f"{'a' in numeros}\n 'a' no se encuentra en la lista" )
